openapi: 3.0.3
info:
  title: Meeting Scheduler API
  version: 1.0.0
  description: API for scheduling meetings and managing user availabilities

servers:
  - url: http://localhost:8001

paths:
  /events:
    post:
      summary: Create Event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventInput'
      responses:
        '201':
          description: Event created

  /events/{event_id}:
    put:
      summary: Update Event
      parameters:
        - in: path
          name: event_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventInput'
      responses:
        '200':
          description: Event updated

    delete:
      summary: Delete Event
      parameters:
        - in: path
          name: event_id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Event deleted

  /events/{event_id}/availability/{user_id}:
    get:
      summary: Get User Availability
      parameters:
        - in: path
          name: event_id
          required: true
          schema:
            type: integer
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User availability data

    post:
      summary: Create User Availability
      parameters:
        - in: path
          name: event_id
          required: true
          schema:
            type: integer
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AvailabilityInput'
      responses:
        '201':
          description: Availability created

    put:
      summary: Update User Availability
      parameters:
        - in: path
          name: event_id
          required: true
          schema:
            type: integer
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AvailabilityInput'
      responses:
        '200':
          description: Availability updated

    delete:
      summary: Delete User Availability
      parameters:
        - in: path
          name: event_id
          required: true
          schema:
            type: integer
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Availability deleted

  /events/{event_id}/recommendation:
    get:
      summary: Get Event Time Recommendation
      parameters:
        - in: path
          name: event_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Best time slot recommendations

components:
  schemas:
    EventInput:
      type: object
      properties:
        title:
          type: string
        organizer_id:
          type: integer
        duration_minutes:
          type: integer
        proposed_slots:
          type: array
          items:
            $ref: '#/components/schemas/TimeSlot'
      required:
        - title
        - organizer_id
        - duration_minutes
        - proposed_slots

    AvailabilityInput:
      type: object
      properties:
        availability:
          type: array
          items:
            $ref: '#/components/schemas/TimeSlot'
      required:
        - availability

    TimeSlot:
      type: object
      properties:
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
      required:
        - start_time
        - end_time
