# Database connections
mysql:
  host: "mysql"
  port: 3306
  username: "xxxxx"
  password: "xxxxx"
  database: "meeting_scheduler"
  parsetime: true
  maxidleconns: 5
  maxopenconns: 10
  connmaxlifetime: 30
  readtimeout: 30
  connectiontimeout: 30
 
# Host and port for different types of connections
connection:
  host: "0.0.0.0"
  port: 8001
  readtimeout: 30
  writetimeout: 30
  idletimeout: 30
